name: common
description: Common resources for the Twitch Extension example.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
