name: extension_ebs
description: An example of the twitch extension for the EBS system.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0
  http: ^1.2.2
  twitch_manager:
    # When depending on this package from a real application you should use:
    #   enhanced_containers: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../../..
  common: 
    path: ../common

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
